# docker-compose.yml

services:
  db:
    container_name: board-app-db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: board-app_development
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - board-app-network

  web:
    container_name: board-app
    build:
      context: .
      dockerfile: Dockerfile.dev # 開発環境用のDockerfileを指定
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/board-app
      - bundle_data:/usr/local/bundle
      - ./tmp:/board-app/tmp
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: board-app_development
      RAILS_ENV: development
    depends_on:
      - db
    networks:
      - board-app-network

volumes:
  db_data:
  bundle_data:

networks:
  board-app-network:
    driver: bridge